server:
  port: 80

spring:
  application:
    name: cloud-orderconsul-service
  cloud:
    consul:
      host: 192.168.218.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
