server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-service


eureka:
  client:
    #表示是否将自己注册进Eureka Server 默认为true
    register-with-eureka: true
    #表示是否从注册中心抓取已有的服务注册信息，单节点无所谓，集群必须配置为true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
      #主机实例名称
      instance-id: consumer80
      #访问路径是否显示ip地址
      prefer-ip-address: true
# 开启hystrix支持
feign:
  hystrix:
    enabled: true
