server:
  port: 7001

spring:
  application:
    name: eureka-service7001

eureka:
  client:
    #false指不会像注册中心注册自己
    register-with-eureka: false
    #false指自己本身就是注册中心，只需维护服务实例，并不需要去检索服务
    fetchRegistry: false
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka
      # 集群搭建，RPC框架的核心：高可用，防止单点故障
#      defaultZone: http://eureka7002.com:7002/eureka
  #server:
        #关闭自我保护机制，保证不可用服务被及时踢除
        #enable-self-preservation: false
        #心跳发送时间2s，默认30s
        #eviction-interval-timer-in-ms: 2000


