server:
  port: 8005

spring:
  application:
    name: cloud-paymentconsul-service
  cloud:
    consul:
      host: 192.168.218.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        心跳协议
        heartbeat:
          enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # \u5F53\u524D\u6570\u636E\u6E90\u64CD\u4F5C\u7C7B\u578B
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql\u9A71\u52A8\u5305
    url: jdbc:mysql://192.168.218.100:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.itoyoung.springcloud.entities

